version: "3.9"

# Gemini Agent API - Containerized deployment
# Run with: podman-compose up -d --build

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL:-}
      - GEMINI_TIMEOUT=${GEMINI_TIMEOUT:-300}
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
    command: >
      uvicorn gemini_agent.server.app:app
      --host 0.0.0.0
      --port 8000
      --reload
    volumes:
      - ./gemini_agent:/app/gemini_agent:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL:-}
      - GEMINI_TIMEOUT=${GEMINI_TIMEOUT:-300}
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
    command: >
      celery -A gemini_agent.server.worker:celery_app worker
      --loglevel=info
      --concurrency=4
    volumes:
      - ./gemini_agent:/app/gemini_agent:ro
    restart: unless-stopped

volumes:
  redis_data:
